# Generated by Django 4.2.3 on 2023-08-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='kind',
            field=models.CharField(choices=[('entire_place', 'Entire Place'), ('private_room', 'Private Room'), ('shared_room', 'Shared Room')], max_length=20),
        ),
    ]
